#+options: toc:nil
#+options: ^:nil
* NNMOF
  
Nueral Network boosted Moment of Fluid

** Note:

    (1) Execute with command
    #+begin_src basj
            mpirun -np (X) (executable) (input)
            #+end_src

           - (X) should be consistant with px*py in input file

           - (executable) is generated by Makefile

           - (input) is the name of the input namelist file, without suffix .namelis
             for example, for file test3.namelist, the (input) should be test3.
             If no (input) is given, it will search for the default input file input.namelist.

    (2) Only HDF5 is supported for input and output field files.

    (3) Only support one ghost cell layer.
        For MPI exchange, always 0 and n(i+1) as halo nodes.
        For centered variable, 0 and n(i+1) are boundary nodes.
        For face variable, 0 and n(i) are boundary nodes.

    (4) Now boundary conditoin only support fixed value Dilichilet and Nuemann.
    The =Field= type contains the BC information. =lohi= indicates the index of the boundary in each 
    direction, =bound_type= is the type of boundary conditoin, 1 means Dilichlet, 2 means Nuemann;
    =bound_value= is the value of the boundary conditoin. The shape of =lohi=, =bound_value= and 
    =bound_type= are =(3,2)=.

** GTD
   
*** Basic VOF[4/4]
- [X] Basic MPI from CaNS
- [X] VOF-PLIC
- [X] Advection of centroid
- [X] MOF

*** MOF [0/3]
- [ ] Fkeas
- [ ] MOF forward data generation
- [ ] Parameters optimization

*** Numerical tests[0/1]
- [ ] Analytic slope
- [ ] Resoncnstruction
- [ ] Zalesak
- [ ] Single vortex

*** Write paper[0/3]
- [ ] Abstract and introduction
- [ ] Describe method
- [ ] Numerical tests

