#+options: toc:nil
#+options: ^:nil
* NNMOF
  
Nueral Network boosted Moment of Fluid

** Installation
The code need several run-time libraries:

- HDF5
- hypre
- Two external MOF libraries (Use to compare with my algorithm)

*** Easy installation
When you work with UNIX based OS, for example, Ubuntu/Linux Mint, 
with =gcc=, =gfortran=, =mpich/openmpi= installed from =apt-get=, 
you should be able to build the essential run-time libraries by

#+begin_src bash
bash libs-install.sh
#+end_src

All libraries are located in =libs= directory.

*** Manual installation
You may compile your own =hdf5= and =hypre=, 
and manually compile two external MOF libraries in =libs= directory. 
It is important to make sure the C, 
Fortran compiler and MPI version are consistent 
while compiling all those libraries.

*** For visualization
There are visualization tool available, 
which replies on =h5py= and =mayavi= library with *Python*. 
To use it, =Python= and correcponding library should be installed as well. 
=Anaconda= is recommanded to install =Python= and libraries.

** Important Note:

*** Makefile

See the Makefile in =test/basics= directory as the example to see how to customize makefile.

The code in =src= directory does not contain main file, 
the main file and other extra code file should be added to the name 
=CASE_SRCS= and makefile.
 

*** Run the code
     Execute with command
    #+begin_src bash
      mpirun -np (X) (executable) (input)
            #+end_src

-   =(X)= should be consistant with =px*py= in input file

-   =(executable)= is generated by Makefile

-   =(input)= is the name of the input namelist file and the field file based on hdf5, without suffix
    for example, for file =test3.namelist=, and the initial field file is =test3.h5=, =(input)= should be =test3=.
    If no =(input)= is given, it will search for the default input file =input.namelist= and =input.h5=.


*** Ghost cells
    -   Only support one ghost cell layer.
    -   For MPI exchange, always 0 and n(i+1) as halo nodes.
    -   For centered variable, 0 and n(i+1) are boundary nodes.
    -   For face variable, 0 and n(i) are boundary nodes.

*** Boundary conditions
    Now boundary conditoin only support fixed value Dilichilet and Nuemann.
    The =Field= type contains the BC information. =lohi= indicates the index of the boundary in each 
    direction, =bound_type= is the type of boundary conditoin, 1 means Dilichlet, 2 means Nuemann;
    =bound_value= is the value of the boundary conditoin. The shape of =lohi=, =bound_value= and 
    =bound_type= are =(3,2)=.

** GTD
   
*** Basic VOF[4/4]
- [X] Basic MPI from CaNS
- [X] VOF-PLIC

*** Fast MOF [6/6]
- [X] Advection of centroid
- [X] MOFSussman
- [X] MOFLemoineAnalyticBFGS
- [X] MOFLemoineAnalyticGaussNewton
- [X] MOFLemoineNumericalBFGS
- [X] Efficient MOF

*** NNMOF[0/3]
- [ ] Fkeas
- [ ] MOF forward data generation
- [ ] Parameters optimization

*** Write paper[1/3]
- [X] Flow solver
- [ ] Debug flow solver
- [ ] FSI

